recipe_dict = {
    'Sauteed Chicken Breast with Pan Sauce': {
        'protein': 'Chicken',
        'substeps': True,
        'ingredients': [['1.5-2 lb.', 'boneless skinless chicken breast, butterflied'],
                        ['3 tsp.', 'seasoning blend of choice'],
                        ['2 tbsp.', 'extra virgin olive oil'],
                        ['2 tbsp.', 'unsalted butter'],
                        ['8 oz.', 'sliced button or portabella mushrooms'],
                        ['one', 'shallot, thinly sliced'],
                        ['2 tsp.', 'balsamic or red wine vinegar'],
                        ['a few sprigs', 'sage and/or thyme'],
                        ['to taste', 'salt and pepper']],
        'steps': {'Prepare the Chicken':
                  ['Season one side of all breasts liberally with seasoning blend and let rest for 15 minutes.',
                   'Turn all breasts over and liberally season other side. Let rest for an additional 15 minutes.',
                   'Heat skillet to medium-high heat. Add olive oil and heat until shimmering.',
                   'Add chicken to pan. Let sit for 7-8 minutes without disturbing.',
                   'Once chicken is a caramelized brown, turn over and let cook for an additional 7-8 minutes.',
                   'Once it reaches an internal temperature of 165° F, remove from heat and cover.'],
                  'Prepare the Pan Sauce':
                  ['In the same pan, add the unsalted butter and let melt.',
                   'Once butter is hot, add shallot and mushrooms.',
                   'When shallot has softened and mushrooms are cooked down, add vinegar and herbs. Salt and pepper to taste.',
                   'Cook for 2-3 minutes. Serve immediately, over chicken.']
                  },
        'veggies': ['Broccoli',
                    'Brussels Sprouts',
                    'Asparagus'],
        'carbs': ['White Rice',
                  'Pearl Couscous']
    },
    'Korean Stir-Fried Chicken Thighs with Rice Cakes': {
        'protein': 'Chicken',
        'substeps': False,
        'ingredients': [['3 tbsp.', 'gochujang'],
                        ['2 tbsp.', 'rice vinegar'],
                        ['2 tsp.', 'gochugaru'],
                        ['1.5 tbsp.', 'soy sauce'],
                        ['2 tbsp.', 'fish sauce'],
                        ['1/4 cu.', 'kimchi juice'],
                        ['six cloves', 'garlic, minced'],
                        ['2 tsp.', 'ginger, minced'],
                        ['1/2 cup', 'scallion whites, thinly sliced'],
                        ['2 tbsp, in parts', 'sesame oil'],
                        ['to taste', 'white pepper and brown sugar'],
                        ['1.5-2 lb.', 'boneless skinless chicken thighs, cut into 1/2" chunks'],
                        ['1 lb.',
                            '*garae-tteok* (Korean cylindrical rice cakes)'],
                        ['2 tbsp.', 'vegetable oil']],
        'steps': ['In a medium-sized bowl, whisk together gochujang, rice vinegar, gochugaru, soy sauce, fish sauce, kimchi juice, garlic, ginger, scallion whites, and 1 tbsp. of the sesame oil. Taste and add white pepper and brown sugar as needed.',
                  'Add chicken thighs and coat thoroughly. Let marinate at least 2 hours.',
                  'Once chicken is marinated, submerge *garae-tteok* in a bowl of room temperature water. Let soak at least 10 minutes.',
                  'Heat large saucepan to medium-high heat and add vegetable oil. Once oil is shimmering, add chicken thighs and all the marinade. Cook for 5-7 minutes. ',
                  'Drain rice cakes and add to the pan. Stir to coat thoroughly.',
                  'Add the other tablespoon of sesame oil and cook for another 10-15 minutes, until rice cakes are soft and chicken is cooked through.'],
        'toppings': ['Sesame Seeds',
                     'Scallion Greens',
                     'Kimchi'],
        'veggies': ['Gai Lan (Chinese Broccoli)',
                    'Baby Bok-Choi'],
        'carbs': ['White Rice']
    },
    'Shrimp Scampi with Orzo': {
        'protein': 'Shrimp',
        'substeps': False,
        'sourceName': 'New York Times',
        'sourceURL': 'https://cooking.nytimes.com/recipes/1020330-shrimp-scampi-with-orzo',
        'ingredients': [['1.5 lb.', 'shrimp, peeled and deveined'],
                        ['3 tbsp.', 'extra virgin olive oil'],
                        ['1 tbsp.', 'lemon zest'],
                        ['1 tbsp.', 'lemon juice'],
                        ['1 tsp.', 'red pepper flakes'],
                        ['to taste', 'salt and black pepper'],
                        ['6 cloves', 'garlic, minced'],
                        ['2 tbsp.', 'unsalted butter'],
                        ['1 cup', 'orzo'],
                        ['1/3 cup', 'dry white wine'],
                        ['2 cups', 'seafood stock or chicken stock'],
                        ['3 tbsp.', 'chopped parsley']],
        'steps': ['In a medium bowl, stir together shrimp, 1 tablespoon olive oil, lemon zest, red-pepper flakes, 1/2 teaspoon salt, 1/4 teaspoon pepper and half of the garlic. Marinate for at least one hour.',
                  'Add butter, remaining olive oil and remaining garlic to a medium skillet set over medium heat. When the butter starts to bubble, add the orzo and ½ teaspoon salt and cook, stirring often, until the orzo is toasted, about 2 minutes, adjusting the heat as necessary to prevent the garlic from burning.',
                  'Carefully add the wine and stir until absorbed, about 1 minute. Stir in stock, reduce heat to low, cover, and cook until orzo is al dente, about 12 minutes.',
                  'Add shrimp in a single layer on top of the orzo. Cook until shrimp is cooked through, 2-4 minutes. Let rest for 2 minutes.'],
        'toppings': ['Chopped Parsley', 'Lemon Juice'],
        'veggies': ['Asparagus',
                    'Broccoli'],
    },
    'Spicy Sausage with Pasta and Red Sauce': {
        'protein': 'Pork',
        'substeps': False,
        'ingredients': [['1 lb.', 'spicy Italian sausage'],
                        ['3 tbsp, in parts', 'extra virgin olive oil'],
                        ['16 oz.', 'sliced white button or portabella mushrooms'],
                        ['One 16 oz. jar',
                            'high quality red pasta sauce, such as *Rao\'s*'],
                        ['1 tsp.', 'red pepper flakes'],
                        ['2 tsp.', 'fennel seeds'],
                        ['1 tsp.', 'dried oregano'],
                        ['12 oz.', 'penne'],
                        ['to taste', 'salt and pepper']],
        'steps': ['In a large pot, submerge sausage in water until just covered. Heat stove on medium-high heat until bubbles begin to form, about 8-10 minutes.',
                  'Remove sausage from heat. Let cool for 2-3 minutes, then slice into 1/2" thick coins. Drain, rinse and dry pot.',
                  'In same pot, heat 2 tbsp. of the olive oil on medium-high heat. Once shimmering add, sausage coins in a single layer.',
                  'Sautee until brown and crisp, about 5-7 minutes. Flip coins and cook for another 5-7 minutes. Remove from heat and transfer sausage to a paper towel-lined plate.',
                  'Turn heat to medium and add remaining tablespoon of olive oil. Add mushrooms and cook for 2-3 minutes.',
                  'Add sauce and stir. Add red pepper flakes, fennel seeds, and oregano. Reduce heat to medium-low.',
                  'Set water to boil for penne. Add 2 tsp. of salt and splash of olive oil. Once boiling, cook until extremely al dente (about 6-7 minutes).',
                  'Before draining pasta, add a 1/2 cu. of the pasta water to the sausage and sauce. Drain pasta completely and add penne to sauce.'],
        'toppings': ['Freshly Grated Parmesan Cheese'],
        'veggies': ['Broccoli',
                    'Asparagus'],
    },
    'Pasta with Sausage, Sage and Butternut Squash': {
        'protein': 'Pork',
        'substeps': False,
        'sourceName': 'New York Times',
        'sourceURL': 'https://cooking.nytimes.com/recipes/1019554-pasta-with-sausage-squash-and-sage-brown-butter',
        'ingredients': [['1 lb.', 'spicy Italian sausage'],
                        ['3 tbsp, in parts', 'extra virgin olive oil'],
                        ['1 lb. (about 3 cu.)',
                            'butternut squash, peeled and cut into 1/2" cubes'],
                        ['6 tbsp.', 'unsalted butter'],
                        ['1 tsp.', 'red pepper flakes'],
                        ['8', 'sage leaves'],
                        ['1/2 cu.', 'grated Parmesan cheese'],
                        ['12 oz.', 'penne'],
                        ['to taste', 'salt and pepper']],
        'steps': ['In a large pot, submerge sausage in water until just covered. Heat stove on medium-high heat until bubbles begin to form, about 8-10 minutes.',
                  'Remove sausage from heat. Let cool for 2-3 minutes, then slice into 1/2" thick coins. Drain, rinse and dry pot.',
                  'In same pot, heat 2 tbsp. of the olive oil on medium-high heat. Once shimmering add, sausage coins in a single layer.',
                  'Sautee until brown and crisp, about 5-7 minutes. Flip coins and cook for another 5-7 minutes. Remove from heat and transfer sausage to a paper towel-lined plate.',
                  'Turn heat to medium and add squash and a pinch of salt. Let cook, stirring briefly and scraping up any browned bits on the bottom of the pan, until browned, 5 to 7 minutes.',
                  'Set water to boil for penne. Add 2 tsp. of salt and splash of olive oil. Once boiling, cook until extremely al dente (about 6-7 minutes).',
                  'Before draining pasta, reserve 1 cup of the pasta water. Drain pasta completely and set aside.',
                  'When the squash is nicely browned, add the butter and sage and cook until the butter is golden, nutty smelling and foaming, just a minute or two, then immediately remove the pan from the heat and add back the sausage.',
                  'Add the pasta to the pan and mix with the brown-butter sauce (if the pasta has cooled off quite a bit, return the pan to low heat while you combine everything). Stir in the cheese, then add pasta water as needed to smooth the sauce. Adjust with salt and pepper.'],
        'toppings': ['Freshly Grated Parmesan Cheese'],
        'veggies': ['Broccoli',
                    'Asparagus'],
    },
    'Creamy Braised White Beans': {
        'protein': 'Vegetarian',
        'substeps': False,
        'sourceName': 'New York Times',
        'sourceURL': 'https://cooking.nytimes.com/recipes/1019982-creamy-braised-white-beans',
        'ingredients': [['1 tbsp.', 'unsalted butter'],
                        ['10-12 cloves', 'garlic, minced'],
                        ['1.5 cu.', 'whole milk'],
                        ['2 15-oz. cans', 'chickpeas, with liquid'],
                        ['2 15-oz. cans', 'white beans, drained and rinsed'],
                        ['1 bunch', 'rainbow Swiss chard, chopped and stems removed'],
                        ['1 tsp.', 'paprika'],
                        ['1/2 tsp.', 'cayenne pepper'],
                        ['1/8 tsp.', 'ground nutmeg'],
                        ['4-6', 'sage leaves'],
                        ['2-3', 'thyme sprigs'],
                        ['to taste', 'salt and pepper']],
        'steps': ['In a medium saucepan, melt the butter over medium-high heat. Add the garlic and let brown for 2-3 minutes.',
                  'Add the milk, chickpeas and their liquid, white beans, thyme, sage, paprika, cayenne pepper and nutmeg and stir to combine. Season generously with salt and pepper.',
                  'When the mixture begins to bubble around the edges of the pan (you don’t want it to come to a full boil), reduce the heat to low and let it simmer, stirring occasionally until it has thickened, about 15 minutes. Season with salt and pepper, to taste.',
                  'If you would like the beans to be more stew-like, mash some of the beans using a potato masher or the back of a spoon.',
                  'Add the chard cook down until reduced, about 5-7 minutes. Adjust again with salt and pepper.'],
        'toppings': ['Freshly Grated Parmesan Cheese'],
        'carbs': ['Crusty Bread']
    },
    'Instant Pot Tex-Mex Chili': {
        'protein': 'Beef',
        'substeps': False,
        'sourceName': 'Amy + Jacky',
        'sourceURL': 'https://www.pressurecookrecipes.com/instant-pot-chili/',
        'ingredients': [['1 tbsp.', 'olive oil'],
                        ['1-1.5 lbs.', 'lean ground beef'],
                        ['1 cup', 'chicken stock'],
                        ['2 tbsp.', 'fish sauce'],
                        ['1 tbsp.', 'soy sauce'],
                        ['1 tsp.', 'unsweetened cocoa powder'],
                        ['4 cloves', 'garlic, minced'],
                        ['1', 'medium white onion, diced'],
                        ['2 15-oz. cans',
                            'red kidney beans, drained and rinsed'],
                        ['1 28-oz. can', 'crushed tomatoes'],
                        ['3 tbsp.', 'tomato paste'],
                        ['2 tbsp.', 'chili powder'],
                        ['1 tbsp.', 'ground cumin'],
                        ['1 tsp.', 'dried oregano'],
                        ['1 tsp.', 'paprika'],
                        ['to taste', 'salt, pepper and brown sugar']],
        'steps': ['Heat IP by turning on Saute Mode. When it reads HOT, add the olive oil.',
                  'Add ground beef and season with salt and pepper. Let cook, stirring occasionally, until beef is browned (about 5-7 minutes). Reserve the juice in a small bowl',
                  'While beef is cooking, create flavor base by whisking together chicken stock, fish sauce, soy sauce, and cocoa powder in a small bowl.',
                  'Add onions, garlic, ground cumin, chili powder, and dried oregano. Saute for 5-7 minutes, until fragrant.',
                  'Pour in a half cup of the flavor base and deglaze.',
                  'Add the kidney beans, remaining flavor base and reserved juices and mix well.',
                  'Add the tomato paste and crushed tomatoes to the top, without mixing. Pressure cook at high pressure for 10 minutes, with natural release.',
                  'If chili is too thin, cook down on saute mode for another few minutes. Season to taste with salt, pepper, and brown sugar.'],
        'toppings': ['Sour Cream', 'Lime Juice', 'Diced Jalapeno', 'Scallions', 'Freshly Grated Cheddar Cheese'],
        'carbs': ['Oyster Crackers', 'Saltines']
    },
    'Green Pozole with Chorizo, Mushrooms and Chard': {
        'protein': 'Pork',
        'substeps': False,
        'sourceName': 'MJ\'s Kitchen',
        'sourceURL': 'https://mjskitchen.com/2014/01/chorizo-mushroom-posole-soup/',
        'ingredients': [['2 15-oz. cans', 'hominy'],
                        ['6-8 cu.', 'chicken stock'],
                        ['1/2 lb.', 'Mexican chorizo, crumbled'],
                        ['1', 'medium white onion, chopped'],
                        ['1 4-oz. can', 'diced green chiles, mild'],
                        ['4-6', 'garlic cloves, minced'],
                        ['1/2 lb.', 'sliced white button mushrooms'],
                        ['1 bunch', 'Swiss chard, chopped and stems removed'],
                        ['1', 'medium white onion, diced'],
                        ['2 15-oz. cans',
                            'red kidney beans, drained and rinsed'],
                        ['1 28-oz. can', 'crushed tomatoes'],
                        ['1 tsp.', 'red chili powder'],
                        ['1 tsp.', 'smoked paprika'],
                        ['1 tsp.', 'dried oregano'],
                        ['1/2 tsp.', 'ground cumin'],
                        ['1/2 tsp.', 'ground coriander'],
                        ['juice', '1 lime'],
                        ['to taste', 'salt and pepper and brown sugar']],
        'steps': ['Heat a large pot on medium heat and add chorizo. Let brown for 2-3 minutes.',
                  'Add onion and saute for an additional 2-3 minutes, until onions begin to soften.',
                  'Add hominy and chicken stock and bring to a boil.',
                  'Add green chiles, mushrooms, garlic, chili powder, smoked paprika, oregano, cumin and coriander. Mix well.',
                  'Reduce to a simmer and let cook for 20 minutes, adding water as needed.',
                  'Add the chard and simmer for another 10 minutes.'],
        'toppings': ['Sour Cream', 'Lime Juice', 'Diced Jalapeno', 'Scallions', 'Cilantro', 'Avocado', 'Queso Fresco or Cotija'],
        'carbs': ['Corn Tortillas']
    },
    'Beef Flautas': {
        'substeps': True,
        'protein': 'Beef',
        'sourceName': 'Hello Fresh',
        'sourceURL': 'https://www.hellofresh.com/recipes/beef-flautas-supreme-60929fe277cc7513912c1eb1',
        'ingredients': [['1', 'yellow onion, thinly sliced, with a small amount minced'],
                        ['1.5 lbs.', 'ground beef'],
                        ['2 tsp.', 'chili powder'],
                        ['1 tsp.', 'ground cumin'],
                        ['1 tsp.', 'ground coriander'],
                        ['1 tsp.', 'oregano'],
                        ['1 tsp.', 'garlic powder'],
                        ['2 tsp.', 'salt'],
                        ['3', 'garlic cloves, minced'],
                        ['2 tbsp.', 'tomato paste'],
                        ['12', 'flour tortillas'],
                        ['1 cu.', 'shredded Mexican cheese'],
                        ['juice', '2 limes'],
                        ['zest', '1 lime, in parts'],
                        ['2', 'Roma tomatoes, diced'],
                        ['8 tbsp.', 'sour cream']],
        'steps': {'Make the Filling':
                  ['Heat a small amount of oil in a large pan over medium-high heat.',
                   'Add sliced onion (reserving the minced onion) and cook until fragrant, 2-3 minutes.'
                   'Add beef, chili powder, cumin, coriander, oregano, garlic powder and salt. Cook until beef is browned, 4-6 minutes.',
                   'Add tomato paste, garlic and 1/2 cup of water. Simmer until mixture is thickened and beef is cooked through. Remove from heat.'],
                  'Make the Flautas':
                  ['Preheat oven to 425 degrees.',
                   'Drizzle tortillas with 2 tbsp. of olive or vegetable oil.',
                   'Add a heaping 1/4 cup of beef filling to each tortilla and top with 1 tbsp. of shredded Mexican cheese. Roll tightly and place seam side-down on a baking sheet. They should be snug next to each other.',
                   'Bake on middle rack until crisp, 10-12 minutes.'],
                  'Make Pico de Gallo':
                  ['Combine tomato, lime juice and half of the zest and minced onion in a small bowl.',
                   'Season to taste with salt.'],
                  'Make Crema':
                  ['Combine sour cream and remaining lime zest in a small bowl.',
                      'Add water 1 tsp. at a time until drizzling consistency.']
                  }
    },
    'Chickpea Tabouleh Bowls': {
        'substeps': True,
        'protein': 'Vegetarian',
        'sourceName': 'Hello Fresh',
        'sourceURL': 'https://www.hellofresh.com/recipes/crispy-chickpea-tabbouleh-bowls-62163c599094e841211b155a',
        'ingredients': [['3', 'bell peppers, diced into 1/2" chunks'],
                        ['2 15-oz. cans', 'chickpeas, drained, rinsed and dried'],
                        ['6 tbsp.', 'extra virgin olive oil'],
                        ['1 tsp.', 'paprika, in parts'],
                        ['1 tsp.', 'smoked paprika, in parts'],
                        ['1 tsp.', 'cayenne pepper, in parts'],
                        ['1 cup.', 'bulgur wheat, farro, or couscous'],
                        ['2', 'lemons, juiced and zested'],
                        ['2', 'Persian or regular cucumbers, diced'],
                        ['2', 'Roma tomatoes, diced'],
                        ['1 bunch', 'scallions, separated into whites and greens and sliced thin'],
                        ['1/2 oz.', 'dill fronds, chopped'],
                        ['8 tbsp.', 'sour cream'],
                        ['1 cup', 'feta cheese, crumbled']],
        'steps': {'Mix the Spice Blend':
                   ['In a small bowl, whisk together the paprika, smoked paprika, and cayenne pepper. Set aside.'],
                   'Roast the Chickpeas and Peppers':
                   ['Preheat oven to 425 degrees Fahrenheit.',
                    'In a medium sized bowl, combine chickpeas, bell peppers, 2 tbsp. of olive oil, 2 tsp. of the spice blend, and 1 tsp. salt. Mix well.',
                    'Transfer to two baking sheets. Roast for 18-20 minutes, until chickpeas are brown and crisped.'],
                   'Prepare the Grains':
                   ['Combine bulgur/farro/couscous with 1 cup of water, the remainder of the spice blend, and 1 tsp. of salt.',
                    'Bring to a boil, then cover and reduce heat to a low simmer. Cook until grains are tender, about 12-15 minutes.'],
                   'Make the Feta Dressing':
                   ['In a small bowl, whisk together the sour cream, half of the feta, and 1 tbsp. of olive oil.',
                    'Add water 1 tsp. at a time until it reaches a drizzling consistency.',
                    'Season to taste with salt and pepper.'],
                   'Make the Tabbouleh':
                  ['In a large bowl, combine the grains, cucumber, tomatoes, scallion whites, remaining feta, dill, lemon juice, lemon zest, 4 tbsp. of olive oil, and 1/2 tsp. of salt.',
                       'Mix well and season with additional salt and pepper if needed.'],
                  'Assemble Bowls':
                  ['Top tabbouleh with roasted peppers, chickpeas and feta dressing.']
                  },
        'toppings': ['Scallion Greens, Lemon Juice']
    },
    'Sheet Pan Feta and Roasted Chickpeas': {
        'substeps': True,
        'protein': 'Vegetarian',
        'sourceName': 'New York Times',
        'sourceURL': 'https://cooking.nytimes.com/recipes/1023371-sheet-pan-feta-with-chickpeas-and-tomatoes',
        'ingredients': [['2 15-oz. cans', 'chickpeas, drained, rinsed and dried'],
                        ['2 pints (16-20 oz.)',
                         'cherry tomatoes, half sliced and half whole'],
                        ['1/2 tsp.', 'paprika'],
                        ['1/2 tsp.', 'smoked paprika'],
                        ['1/2 tsp.', 'cayenne pepper'],
                        ['2 8-oz. blocks', 'sheep\'s milk feta, quartered'],
                        ['1 tsp.', 'Kosher salt'],
                        ['2', 'shallots, thinly sliced'],
                        ['1/4 cu.', 'extra virgin olive oil'],
                        ['1 tsp.', 'red pepper flakes'],
                        ['2 tbsp.', 'honey']],
        'steps': {'Prep the Feta, Tomatoes and Shallot':
                  ['Preheat oven to 425 degrees Fahrenheit.',
                   'In a medium sized bowl, combine tomatoes, shallot, honey, chile flakes, and remaining olive oil. Season with salt and stir well.',
                   'On another baking sheet lie the feta blocks flat and cover with tomato and shallots in a single layer.',
                   'Roast until feta is soft and tomatoes blister, about 30-35 minutes.'],
                  'Prep the Chickpeas:':
                  ['In a small bowl, whisk together the paprika, smoked paprika, and cayenne pepper.',
                   'In a medium sized bowl, combine chickpeas, 2 tbsp. of olive oil, spice blend, and 1 tsp. salt. Mix well.',
                   'Transfer to a separate large baking sheet. Roast for 18-20 minutes, until chickpeas are brown and crisped.'],
                  },
        'veggies': ['Greek Salad'],
        'carbs': ['Pita', 'Lavash']
    },
    'Instant Pot Caldo de Res': {
        'substeps': False,
        'protein': 'Beef',
        'sourceName': 'Thai Caliente',
        'sourceURL': 'https://thaicaliente.com/instant-pot-caldo-de-res-mexican-beef-soup/',
        'ingredients': [['1.5 lbs.', 'chuck roast, cut into chunks, with bones if possible'],
                        ['1/2', 'white onion, leave halved'],
                        ['4', 'garlic cloves, whole'],
                        ['6-8 cups', 'water'],
                        ['1 tbsp.', 'salt'],
                        ['1', 'Russet potato, peeled cut into chunks'],
                        ['2', 'carrots, cut into three pieces'],
                        ['1/3', 'head of cabbage, cut into large chunks'],
                        ['2', 'corns on the cob, halved']],
        'steps': ['Add beef (with bones if possible), onion, garlic, water and salt to Instant Pot. Cook at pressure for 30 minutes.',
                  'Quick release pressure and remove onion and garlic cloves. Skim fat from top if necessary. If beef is still tough, pressure cook for an additional 10 minutes.',
                  'Remove beef from Instant Pot.',
                  'Add potato, carrots, cabbage and corn. If liquid goes above max line, remove some liquid. Cook at pressure for 3 minutes. Quick release.'],
        'toppings': ['Tortillas', 'Lime Wedges', 'Sour Cream', 'Cotija', 'Hot Sauce']
    },
    'Instant Pot Ham and Potato Soup': {
        'substeps': False,
        'protein': 'Pork',
        'sourceName': 'Karen Rankin',
        'sourceURL': 'https://www.myrecipes.com/recipe/ham-and-potato-soup',
        'ingredients': [['2 lbs.', 'Yukon baby gold potatoes, halved'],
                        ['1', 'medium yellow onion, chopped'],
                        ['2 stalks', 'celery, chopped'],
                        ['2 tbsp.', 'olive oil'],
                        ['2 1-lb.', 'smoked ham hocks'],
                        ['4 cups', 'low sodium chicken stock'],
                        ['1/2 cup', 'heavy cream'],
                        ['1 tsp.', 'Kosher salt'],
                        ['1/2 tsp.', 'black pepper']],
        'steps': ['Turn Instant Pot to saute mode. When hot, add oil, onion, celery and garlic. Cook 6-8 minutes, until onions soften.',
                  'Add ham hocks and stock. Close and cook at pressure fo 20 minutes. Quick release.',
                  'Remove ham hocks and transfer to a cutting board. When cool, remove meat and fat from hocks. Chop meat and discard fat.',
                  'Mash potato mixture until desired consistency. Add back hock meat and add heavy cream, salt and pepper.'],
        'toppings': ['Freshly Grated Cheddar Cheese', 'Sour Cream', 'Scallions']

    },
    'Creamy Spinach-Artichoke Chicken Stew': {
        'substeps': False,
        'protein': 'Chicken',
        'sourceName': 'New York Times',
        'sourceURL': 'https://cooking.nytimes.com/recipes/1021794-creamy-spinach-artichoke-chicken-stew',
        'ingredients': [
            ['2 tbsp.', 'unsalted butter'],
            ['1 large', 'yellow or red onion, finely chopped'],
            ['to taste', 'Kosher salt and black pepper'],
            ['3', 'celery stalks, chopped'],
            ['8', 'garlic cloves, smashed and chopped'],
            ['2 cu.', 'chicken stock'],
            ['¾ cu.', 'white wine'],
            ['2 lbs.', 'boneless, skinless chicken thighs'],
            ['½ lemon', 'juiced (about 1½ tbsp)'],
            ['1 tsp', 'chili flakes'],
            ['1 (10-ounce) package', 'frozen cut spinach'],
            ['1 (12-ounce) jar', 'marinated artichoke hearts, drained'],
            ['½ cup', 'cream cheese (about 4 ounces)'],
            ['½ cup finely chopped', 'fresh dill']
        ],
        'steps': ['Melt the butter in a Dutch oven on medium-high heat. Add onion, season with salt and cook 5-7 mins.',
                  'Add celery and cook for an additional 5 minutes, then add the garlic.',
                  'Add stock and wine, bring to a bubble.',
                  'Add chicken thighs, lemon juice, chili flakes, 1 tsp salt and lots of black pepper. Mix to combine and bring to a boil.',
                  'Reduce the heat to maintain a low simmer and simmer, uncovered, for 20 minutes.',
                  'Add frozen spinach and artichoke hearts, then increase the heat to medium-high.',
                  'Stir to defrost spinach. When the spinach is warm, reduce heat and simmer for 10-15 minutes.',
                  'Add cream cheese and dill. Shred chicken using two forks.'],
        'toppings': ['Scallions', 'Freshly Grated Parmesan Cheese'],
        'carbs': ['Crusty Bread']
    },

    'Spicy Sesame Noodles With Chicken and Peanuts': {
        'substeps': True,
        'protein': 'Chicken',
        'sourceName': 'New York Times',
        'sourceURL': 'https://cooking.nytimes.com/recipes/1020732-spicy-sesame-noodles-with-chicken-and-peanuts',
        'ingredients': [
            ['1½ tbsp.', 'chili flakes'],
            ['1½ tbsp.', 'low-sodium soy sauce'],
            ['1½ tsp.', 'toasted sesame oil, plus more as needed'],
            ['to taste', 'Kosher salt and black pepper'],
            ['½ cup plus 1 tbsp', 'neutral oil, like grapeseed or vegetable'],
            ['6 tbsp.', 'roasted, salted peanuts, coarsely chopped'],
            ['1 tbsp.', 'orange zest'],
            ['1 lb.', 'ground chicken'],
            ['six cloves', 'garlic, minced'],
            ['1 in.', 'ginger, minced'],
            ['10 to 12 ounces', 'fresh udon noodles'],
            ['3 tbsp.', 'finely chopped chives']
        ],
        'steps': {
            'Make the Chili Oil': ['Stir together the chili flakes, soy sauce and sesame oil in a heatproof bowl.',
                                   'Heat a large skillet over medium. Cook 1/2 cu. of oil, peanuts and orange zest, 3-5 min. until peanuts are bubbling.',
                                   'Pour the contents of the skillet over the chili flakes mixture.'],
            'Make the Chicken and Udon': ['In the same skillet as the oil, heat the remaining tablespoon of oil. Add garlic and ginger and saute 2-3 min.',
                                          'Add ground chicken and season heavily with salt and pepper. Flatten and press down on chicken until browned, 5-7 min., then break up chicken into small pieces.',
                                          'Cook udon according to package directions.'
                                          'Add chili oil to coat chicken, scraping bits from the bottom of the pan.',
                                          'Add noodles and toss with additional chili oil.'
                                          ]
        },
        'toppings': ['Diced Cucumber', 'Chopped Cilantro', 'Sliced Scallions']
    }
}
